[package]
name = "burn"
version = "0.1.0"
authors = ["Filip Gospodinov <f@gospodinov.ch>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.30.0"
clap = { version = "4.3.23", features = [ "derive" ] }
