[package]
name = "burn"
version = "0.1.0"
authors = ["Filip Gospodinov <f@gospodinov.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.29.1"
clap = { version = "4.1.8", features = [ "derive" ] }
